/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package frontend;

import backend.Cliente;
import backend.Pedido;
import backend.Producto;
import java.util.List;
import javax.swing.JComboBox;
import org.bson.Document;

/**
 *
 * @author toapa
 */
public class AdquirirProductoJPanel extends javax.swing.JPanel {
private List<Document> productos;
    /**
     * Creates new form FacturaJPanel
     */
    public AdquirirProductoJPanel() {
        initComponents();
        
        cargarProductosDesdeBaseDeDatos();
        cargarProductosEnComboBox();
    }
    
private void cargarProductosDesdeBaseDeDatos() {
    Producto producto = new Producto("", "", 0, 0);
    productos = producto.consultarProductosBDD();
}

private void cargarProductosEnComboBox() {
    // Limpia el combobox por si ya contiene elementos
    jComboBoxPedido.removeAllItems();
    
    // Recorre la lista de productos recuperados y los agrega al combobox
    for (Document doc : productos) {
        String nombreProducto = doc.getString("Producto");
        jComboBoxPedido.addItem(nombreProducto);
    }   
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextFieldBuscar = new javax.swing.JTextField();
        jButtonBuscar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldTelefono = new javax.swing.JTextField();
        jTextFieldNombres = new javax.swing.JTextField();
        jTextFieldEmail = new javax.swing.JTextField();
        jTextFieldApellidos = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabelProducto = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabelPrecio = new javax.swing.JLabel();
        jComboBoxPedido = new javax.swing.JComboBox<>();
        jLabelCodigo = new javax.swing.JLabel();
        jButtonEliminar = new javax.swing.JButton();
        jButtonConfirmar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPaneDescripcion = new javax.swing.JTextPane();

        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(570, 660));
        setPreferredSize(new java.awt.Dimension(570, 660));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        add(jTextFieldBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 20, 162, 30));

        jButtonBuscar.setForeground(new java.awt.Color(0, 153, 255));
        jButtonBuscar.setText("Buscar");
        jButtonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarActionPerformed(evt);
            }
        });
        add(jButtonBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 20, 70, 30));

        jLabel1.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 204));
        jLabel1.setText("ADQUIRIR PRODUCTOS");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, -1, -1));

        jTextFieldTelefono.setPreferredSize(new java.awt.Dimension(180, 32));
        add(jTextFieldTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 280, 180, 32));

        jTextFieldNombres.setPreferredSize(new java.awt.Dimension(180, 32));
        jTextFieldNombres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNombresActionPerformed(evt);
            }
        });
        add(jTextFieldNombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 130, 180, 32));

        jTextFieldEmail.setPreferredSize(new java.awt.Dimension(180, 32));
        add(jTextFieldEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 230, 180, 32));

        jTextFieldApellidos.setPreferredSize(new java.awt.Dimension(180, 32));
        add(jTextFieldApellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 180, 180, 32));

        jLabel2.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 153, 204));
        jLabel2.setText("Seleccione el Producto:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 80, -1, -1));

        jLabelProducto.setText("*NombreProducto*");
        add(jLabelProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 360, 110, 20));

        jLabel4.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 153, 204));
        jLabel4.setText("Telf:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 290, -1, -1));

        jLabel6.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 153, 204));
        jLabel6.setText("Nombres:");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, -1, -1));

        jLabel7.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 153, 204));
        jLabel7.setText("Apellidos:");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 190, -1, -1));

        jLabel9.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 153, 204));
        jLabel9.setText("E-mail:");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 240, -1, -1));

        jLabel10.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 153, 204));
        jLabel10.setText("Datos Adicionales del Producto");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 330, -1, -1));

        jLabelPrecio.setText("*Precio*");
        add(jLabelPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 390, 50, 20));

        jComboBoxPedido.setPreferredSize(new java.awt.Dimension(180, 32));
        jComboBoxPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxPedidoActionPerformed(evt);
            }
        });
        add(jComboBoxPedido, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 70, 180, 32));

        jLabelCodigo.setText("*Código Producto*");
        add(jLabelCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 420, 110, 20));

        jButtonEliminar.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        jButtonEliminar.setForeground(new java.awt.Color(0, 153, 204));
        jButtonEliminar.setText("Eliminar Pedido");
        jButtonEliminar.setPreferredSize(new java.awt.Dimension(180, 32));
        jButtonEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEliminarActionPerformed(evt);
            }
        });
        add(jButtonEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 590, -1, -1));

        jButtonConfirmar.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        jButtonConfirmar.setForeground(new java.awt.Color(0, 153, 204));
        jButtonConfirmar.setText("Confirmar Pedido");
        jButtonConfirmar.setPreferredSize(new java.awt.Dimension(180, 32));
        jButtonConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConfirmarActionPerformed(evt);
            }
        });
        add(jButtonConfirmar, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 550, -1, -1));

        jLabel5.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 153, 204));
        jLabel5.setText("Código:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 420, -1, -1));

        jLabel8.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 153, 204));
        jLabel8.setText("Producto:");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 360, -1, -1));

        jLabel11.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 153, 204));
        jLabel11.setText("Precio:");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 390, -1, -1));

        jScrollPane1.setViewportView(jTextPaneDescripcion);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 450, 140, 80));
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonBuscarActionPerformed

    private void jButtonEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEliminarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonEliminarActionPerformed

    private void jTextFieldNombresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNombresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNombresActionPerformed

    private void jComboBoxPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxPedidoActionPerformed
   // Obtener el índice del producto seleccionado en el JComboBox
    int selectedIndex = jComboBoxPedido.getSelectedIndex();
    
    // Verificar que el índice sea válido y que haya productos cargados
    if (selectedIndex >= 0 && selectedIndex < productos.size()) {
        // Obtener el Document correspondiente al producto seleccionado
        Document selectedProduct = productos.get(selectedIndex);
        
        // Obtener el nombre, precio y código del producto del Document
        String nombreProducto = selectedProduct.getString("Producto");
        String descripcion = selectedProduct.getString("Descripción");
        double precioProducto = selectedProduct.getDouble("Precio");
        double codigoProducto = selectedProduct.getDouble("Código");
        
        // Actualizar los JLabels con la información del producto seleccionado
        jLabelProducto.setText(nombreProducto);
       jTextPaneDescripcion.setText(descripcion);
        jLabelPrecio.setText(String.valueOf(precioProducto));
        jLabelCodigo.setText(String.valueOf(codigoProducto));
        
    }    }//GEN-LAST:event_jComboBoxPedidoActionPerformed

    private void jButtonConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConfirmarActionPerformed
       String  nombres = jTextFieldNombres.getText();
       String apellidos = jTextFieldApellidos.getText();
       String email = jTextFieldEmail.getText();
       String telefono = jTextFieldTelefono.getText();
       String producto = jLabelProducto.getText();
       String descripcion = jTextPaneDescripcion.getText();
       Double precio = Double.parseDouble(jLabelPrecio.getText());
       Double codigo = Double.parseDouble(jLabelCodigo.getText());
       
       Cliente cliente = new Cliente(nombres,apellidos,email,telefono);
       Producto producto1 = new Producto(producto,descripcion,precio,codigo);
       
       Pedido pedido = new Pedido(0,cliente,producto1);
       
       pedido.agregarPedidoBDD();
       
       jTextFieldNombres.setText("");
       jTextFieldApellidos.setText("");
       jTextFieldEmail.setText("");
       jTextFieldTelefono.setText("");
       jLabelProducto.setText("");
       jTextPaneDescripcion.setText("");
       jLabelPrecio.setText("");
       jLabelCodigo.setText("");
       
    }//GEN-LAST:event_jButtonConfirmarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBuscar;
    private javax.swing.JButton jButtonConfirmar;
    private javax.swing.JButton jButtonEliminar;
    private javax.swing.JComboBox<String> jComboBoxPedido;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelCodigo;
    private javax.swing.JLabel jLabelPrecio;
    private javax.swing.JLabel jLabelProducto;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextFieldApellidos;
    private javax.swing.JTextField jTextFieldBuscar;
    private javax.swing.JTextField jTextFieldEmail;
    private javax.swing.JTextField jTextFieldNombres;
    private javax.swing.JTextField jTextFieldTelefono;
    private javax.swing.JTextPane jTextPaneDescripcion;
    // End of variables declaration//GEN-END:variables
}
