/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package frontend;

import backend.Producto;

/**
 *
 * @author toapa
 */
public class AgregarProductoJPanel extends javax.swing.JPanel {

    /**
     * Creates new form AgregarProductoJPanel
     */
    public AgregarProductoJPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelVistaP1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldCodigo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldPrecio = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldNombre = new javax.swing.JTextField();
        jButtonEliminar = new javax.swing.JButton();
        jButtonAgregar = new javax.swing.JButton();
        jTextPaneDescripcion = new javax.swing.JTextPane();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldCodigo1 = new javax.swing.JTextField();

        setPreferredSize(new java.awt.Dimension(570, 660));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelVistaP1.setBackground(new java.awt.Color(255, 255, 255));
        jPanelVistaP1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 153, 255));
        jLabel2.setText("Precio:");
        jPanelVistaP1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 250, -1, -1));

        jTextFieldCodigo.setPreferredSize(new java.awt.Dimension(250, 32));
        jPanelVistaP1.add(jTextFieldCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 310, -1, -1));

        jLabel3.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 153, 255));
        jLabel3.setText("Nombre del Producto:");
        jPanelVistaP1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 70, -1, -1));

        jLabel4.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 153, 255));
        jLabel4.setText("Descripción:");
        jPanelVistaP1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 130, -1, -1));

        jTextFieldPrecio.setPreferredSize(new java.awt.Dimension(100, 32));
        jPanelVistaP1.add(jTextFieldPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 240, -1, -1));

        jLabel5.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 153, 255));
        jLabel5.setText("Código del Producto:");
        jPanelVistaP1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 320, -1, -1));

        jTextFieldNombre.setPreferredSize(new java.awt.Dimension(250, 32));
        jTextFieldNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNombreActionPerformed(evt);
            }
        });
        jPanelVistaP1.add(jTextFieldNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 60, -1, -1));

        jButtonEliminar.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        jButtonEliminar.setForeground(new java.awt.Color(0, 153, 255));
        jButtonEliminar.setText("Eliminar Producto");
        jButtonEliminar.setPreferredSize(new java.awt.Dimension(100, 30));
        jButtonEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEliminarActionPerformed(evt);
            }
        });
        jPanelVistaP1.add(jButtonEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 530, 130, 30));

        jButtonAgregar.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        jButtonAgregar.setForeground(new java.awt.Color(0, 153, 255));
        jButtonAgregar.setText("Agregar");
        jButtonAgregar.setPreferredSize(new java.awt.Dimension(100, 30));
        jButtonAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAgregarActionPerformed(evt);
            }
        });
        jPanelVistaP1.add(jButtonAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 390, 130, 30));
        jPanelVistaP1.add(jTextPaneDescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 120, 250, 80));

        jLabel6.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 153, 255));
        jLabel6.setText("AGREGAR PRODUCTO");
        jPanelVistaP1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 20, -1, -1));

        jLabel7.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 153, 255));
        jLabel7.setText("Si desea eliminar un producto, coloque el código:");
        jPanelVistaP1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 460, -1, -1));

        jTextFieldCodigo1.setPreferredSize(new java.awt.Dimension(250, 32));
        jPanelVistaP1.add(jTextFieldCodigo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 490, -1, -1));

        add(jPanelVistaP1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 570, 660));
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNombreActionPerformed

    private void jButtonAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAgregarActionPerformed
        String nombre = jTextFieldNombre.getText();
        String descripcion = jTextPaneDescripcion.getText();
        Double precio = Double.parseDouble(jTextFieldPrecio.getText());
        Double codigo = Double.parseDouble(jTextFieldCodigo.getText());
          
        Producto producto = new Producto(nombre,descripcion,precio,codigo);
        ProductosJPanel jpanelProductos = new ProductosJPanel(); 
        producto.agregarProductoBDD();   
        
        jTextFieldNombre.setText("");
        jTextPaneDescripcion.setText("");
        jTextFieldPrecio.setText("");
        jTextFieldCodigo.setText("");
    }//GEN-LAST:event_jButtonAgregarActionPerformed

    private void jButtonEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEliminarActionPerformed
        Double codigo = Double.parseDouble(jTextFieldCodigo1.getText());  
        Producto producto = new Producto("","",0,codigo);
        producto.eliminarProductoBDD(codigo);     
    }//GEN-LAST:event_jButtonEliminarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAgregar;
    private javax.swing.JButton jButtonEliminar;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanelVistaP1;
    private javax.swing.JTextField jTextFieldCodigo;
    private javax.swing.JTextField jTextFieldCodigo1;
    private javax.swing.JTextField jTextFieldNombre;
    private javax.swing.JTextField jTextFieldPrecio;
    private javax.swing.JTextPane jTextPaneDescripcion;
    // End of variables declaration//GEN-END:variables
}
