/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frontend;

/**
 *
 * @author labctr
 */
public class MenuJFrame extends javax.swing.JFrame {

    /**
     * Creates new form MenuJFrame
     */
    private ProductosJPanel jpanelProductos;
    public MenuJFrame() {
        initComponents();
        jpanelProductos = new ProductosJPanel();
        jpanelProductos.setSize(jPanelVista.getSize());
        jpanelProductos.setLocation(0, 0);
        jPanelVista.removeAll();
        jPanelVista.add(jpanelProductos);
        jPanelVista.revalidate();
        jPanelVista.repaint();
        
        /*  jpanelMenu= new MenuJPanel();
        jpanelMenu.setSize(jPanelVista.getSize());
        jpanelMenu.setLocation(0, 0);
        jPanelVista.removeAll();
        jPanelVista.add(jpanelMenu);
        jPanelVista.revalidate();
        jPanelVista.repaint();
        */
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jButtonSalir = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jButtonProductos = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButtonCFactura = new javax.swing.JButton();
        jButtonPedidos = new javax.swing.JButton();
        jButtonFactura = new javax.swing.JButton();
        jButtonAdquirir = new javax.swing.JButton();
        jPanelVista = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 700));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setPreferredSize(new java.awt.Dimension(800, 45));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonSalir.setBackground(new java.awt.Color(255, 0, 0));
        jButtonSalir.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        jButtonSalir.setForeground(new java.awt.Color(255, 255, 255));
        jButtonSalir.setText("Salir");
        jButtonSalir.setPreferredSize(new java.awt.Dimension(85, 45));
        jButtonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalirActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(715, 0, -1, 40));

        jLabel1.setFont(new java.awt.Font("Roboto", 3, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 153, 255));
        jLabel1.setText("MACHINE Z");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(371, 14, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 40));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setPreferredSize(new java.awt.Dimension(225, 650));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonProductos.setBackground(null);
        jButtonProductos.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        jButtonProductos.setForeground(new java.awt.Color(51, 153, 255));
        jButtonProductos.setText("Productos");
        jButtonProductos.setBorder(null);
        jButtonProductos.setPreferredSize(new java.awt.Dimension(225, 50));
        jButtonProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonProductosActionPerformed(evt);
            }
        });
        jPanel3.add(jButtonProductos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 225, 50));

        jLabel2.setIcon(new javax.swing.ImageIcon("./src/main/java/resources/Fondo.png")
        );
        jLabel2.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jLabel2AncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 310, 230, 350));

        jLabel3.setBackground(null);
        jLabel3.setFont(new java.awt.Font("Roboto", 3, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 153, 255));
        jLabel3.setText("Menú");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, -1, -1));

        jButtonCFactura.setBackground(null);
        jButtonCFactura.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        jButtonCFactura.setForeground(new java.awt.Color(51, 153, 255));
        jButtonCFactura.setText("Consultar Factura");
        jButtonCFactura.setBorder(null);
        jButtonCFactura.setPreferredSize(new java.awt.Dimension(225, 50));
        jButtonCFactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCFacturaActionPerformed(evt);
            }
        });
        jPanel3.add(jButtonCFactura, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 225, 50));

        jButtonPedidos.setBackground(null);
        jButtonPedidos.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        jButtonPedidos.setForeground(new java.awt.Color(51, 153, 255));
        jButtonPedidos.setText("Consultar Pedidos");
        jButtonPedidos.setBorder(null);
        jButtonPedidos.setPreferredSize(new java.awt.Dimension(225, 50));
        jButtonPedidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPedidosActionPerformed(evt);
            }
        });
        jPanel3.add(jButtonPedidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 225, 50));

        jButtonFactura.setBackground(null);
        jButtonFactura.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        jButtonFactura.setForeground(new java.awt.Color(51, 153, 255));
        jButtonFactura.setText("Generar Factura");
        jButtonFactura.setBorder(null);
        jButtonFactura.setPreferredSize(new java.awt.Dimension(225, 50));
        jButtonFactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFacturaActionPerformed(evt);
            }
        });
        jPanel3.add(jButtonFactura, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 225, 50));

        jButtonAdquirir.setBackground(null);
        jButtonAdquirir.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        jButtonAdquirir.setForeground(new java.awt.Color(51, 153, 255));
        jButtonAdquirir.setText("Adquirir Productos");
        jButtonAdquirir.setBorder(null);
        jButtonAdquirir.setPreferredSize(new java.awt.Dimension(225, 50));
        jButtonAdquirir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAdquirirActionPerformed(evt);
            }
        });
        jPanel3.add(jButtonAdquirir, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 225, 50));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 225, 660));

        jPanelVista.setBackground(new java.awt.Color(255, 255, 255));
        jPanelVista.setPreferredSize(new java.awt.Dimension(570, 660));
        jPanelVista.setRequestFocusEnabled(false);

        javax.swing.GroupLayout jPanelVistaLayout = new javax.swing.GroupLayout(jPanelVista);
        jPanelVista.setLayout(jPanelVistaLayout);
        jPanelVistaLayout.setHorizontalGroup(
            jPanelVistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 570, Short.MAX_VALUE)
        );
        jPanelVistaLayout.setVerticalGroup(
            jPanelVistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 660, Short.MAX_VALUE)
        );

        jPanel1.add(jPanelVista, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 40, 570, 660));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalirActionPerformed
        dispose();
    }//GEN-LAST:event_jButtonSalirActionPerformed

    private void jLabel2AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jLabel2AncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel2AncestorAdded

    private void jButtonProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonProductosActionPerformed
        jpanelProductos = new ProductosJPanel();
        jpanelProductos.setSize(jPanelVista.getSize());
        jpanelProductos.setLocation(0, 0);
        jPanelVista.removeAll();
        jPanelVista.add(jpanelProductos);
        jPanelVista.revalidate();
        jPanelVista.repaint();
    }//GEN-LAST:event_jButtonProductosActionPerformed

    private void jButtonCFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCFacturaActionPerformed
      
    }//GEN-LAST:event_jButtonCFacturaActionPerformed

    private void jButtonPedidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPedidosActionPerformed
      ConsultarPedidoJPanel consulta = new ConsultarPedidoJPanel();
        consulta.setSize(jPanelVista.getSize());
        consulta.setLocation(0, 0);
        jPanelVista.removeAll();
        jPanelVista.add(consulta);
        jPanelVista.revalidate();
        jPanelVista.repaint();
    }//GEN-LAST:event_jButtonPedidosActionPerformed

    private void jButtonFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFacturaActionPerformed
        FacturaJPanel factura = new FacturaJPanel();
        factura.setSize(jPanelVista.getSize());
        factura.setLocation(0, 0);
        jPanelVista.removeAll();
        jPanelVista.add(factura);
        jPanelVista.revalidate();
        jPanelVista.repaint();
    }//GEN-LAST:event_jButtonFacturaActionPerformed

    private void jButtonAdquirirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAdquirirActionPerformed
         AdquirirProductoJPanel adquirir = new AdquirirProductoJPanel();
        adquirir.setSize(jPanelVista.getSize());
        adquirir.setLocation(0, 0);
        jPanelVista.removeAll();
        jPanelVista.add(adquirir);
        jPanelVista.revalidate();
        jPanelVista.repaint();

    }//GEN-LAST:event_jButtonAdquirirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAdquirir;
    private javax.swing.JButton jButtonCFactura;
    private javax.swing.JButton jButtonFactura;
    private javax.swing.JButton jButtonPedidos;
    private javax.swing.JButton jButtonProductos;
    private javax.swing.JButton jButtonSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanelVista;
    // End of variables declaration//GEN-END:variables
}
