/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package frontend;

import backend.Producto;
import java.awt.Component;
import java.awt.GridLayout;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.List;
import javax.swing.BoxLayout;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JMenuItem;
import javax.swing.JPopupMenu;
import javax.swing.SwingConstants;
import org.bson.Document;

/**
 *
 * @author toapa
 */
public class ProductosJPanel extends javax.swing.JPanel {
private List<Document> productos;
    /**
     * Creates new form ProductosJPanel
     */
    public ProductosJPanel() {
    initComponents();
    cargarProductosDesdeBaseDeDatos();
    agregarLabelsProductos();
     jPanelGrind.setLayout(new GridLayout(0, 2)); 
    }
     
  
 private void cargarProductosDesdeBaseDeDatos() {
        Producto producto = new Producto("", "", 0, 0);
        productos = producto.consultarProductosBDD();
    }

private void agregarLabelsProductos() {
    for (Document doc : productos) {
        String nombreProducto = doc.getString("Producto");
        String descripcion = doc.getString("Descripción");
        double precio = doc.getDouble("Precio");
        double codigoProducto = doc.getDouble("Código");

        JLabel labelProducto = new JLabel(nombreProducto);
        labelProducto.setHorizontalAlignment(SwingConstants.CENTER);
        labelProducto.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseEntered(MouseEvent e) {
                // Mostrar la información en el jPanelDescripcion
                actualizarPanelDescripcion(nombreProducto, descripcion, precio, codigoProducto);
            }

            @Override
            public void mouseExited(MouseEvent e) {
                // Limpiar el jPanelDescripcion cuando el ratón sale del JLabel
                limpiarPanelDescripcion();
            }
        });

        jPanelGrind.add(labelProducto); // Agregar la etiqueta al panel
    }
}

private void actualizarPanelDescripcion(String nombreProducto, String descripcion, double precio, double codigoProducto) {
    jPanelDescripcion.removeAll();
    
    JLabel labelNombre = new JLabel("Producto: " + nombreProducto);
    JLabel labelDescripcion = new JLabel("Descripción: " + descripcion);
    JLabel labelPrecio = new JLabel("Precio: " + precio);
    JLabel labelCodigo = new JLabel("Código: " + codigoProducto);

    // Establecer el diseño del panel de descripción como BoxLayout con alineación centrada
    jPanelDescripcion.setLayout(new BoxLayout(jPanelDescripcion, BoxLayout.Y_AXIS));

    // Configurar la alineación de los labels
    labelNombre.setAlignmentX(Component.CENTER_ALIGNMENT);
    labelDescripcion.setAlignmentX(Component.CENTER_ALIGNMENT);
    labelPrecio.setAlignmentX(Component.CENTER_ALIGNMENT);
    labelCodigo.setAlignmentX(Component.CENTER_ALIGNMENT);

    // Agregar los labels al panel de descripción
    jPanelDescripcion.add(labelNombre);
    jPanelDescripcion.add(labelDescripcion);
    jPanelDescripcion.add(labelPrecio);
    jPanelDescripcion.add(labelCodigo);

    jPanelDescripcion.revalidate();
    jPanelDescripcion.repaint();
}

private void limpiarPanelDescripcion() {
    jPanelDescripcion.removeAll();
    jPanelDescripcion.revalidate();
    jPanelDescripcion.repaint();
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanelVistaP = new javax.swing.JPanel();
        jButtonBuscar = new javax.swing.JButton();
        jTextFieldBuscar = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jButtonAgregarProducto = new javax.swing.JButton();
        jPanelGrind = new javax.swing.JPanel();
        jPanelDescripcion = new javax.swing.JPanel();

        jLabel1.setText("jLabel1");

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(570, 660));
        setMinimumSize(new java.awt.Dimension(570, 660));
        setPreferredSize(new java.awt.Dimension(570, 660));
        addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                formAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelVistaP.setBackground(new java.awt.Color(255, 255, 255));

        jButtonBuscar.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jButtonBuscar.setForeground(new java.awt.Color(0, 153, 255));
        jButtonBuscar.setText("Buscar");
        jButtonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarActionPerformed(evt);
            }
        });

        jTextFieldBuscar.setText("Busca Algo!");

        jLabel14.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 153, 255));
        jLabel14.setText("PRODUCTOS");

        jButtonAgregarProducto.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        jButtonAgregarProducto.setForeground(new java.awt.Color(0, 153, 255));
        jButtonAgregarProducto.setText("Agregar Producto");
        jButtonAgregarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAgregarProductoActionPerformed(evt);
            }
        });

        jPanelGrind.setBackground(new java.awt.Color(255, 255, 255));
        jPanelGrind.setForeground(new java.awt.Color(0, 153, 255));

        jPanelDescripcion.setBackground(new java.awt.Color(255, 255, 255));
        jPanelDescripcion.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanelVistaPLayout = new javax.swing.GroupLayout(jPanelVistaP);
        jPanelVistaP.setLayout(jPanelVistaPLayout);
        jPanelVistaPLayout.setHorizontalGroup(
            jPanelVistaPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelDescripcion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanelVistaPLayout.createSequentialGroup()
                .addGroup(jPanelVistaPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelVistaPLayout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addComponent(jLabel14)
                        .addGap(122, 122, 122)
                        .addGroup(jPanelVistaPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanelVistaPLayout.createSequentialGroup()
                                .addGap(160, 160, 160)
                                .addComponent(jButtonBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanelVistaPLayout.createSequentialGroup()
                        .addGap(215, 215, 215)
                        .addComponent(jButtonAgregarProducto))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelVistaPLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanelGrind, javax.swing.GroupLayout.PREFERRED_SIZE, 417, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(78, 78, 78)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelVistaPLayout.setVerticalGroup(
            jPanelVistaPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelVistaPLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanelVistaPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelVistaPLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel14))
                    .addComponent(jTextFieldBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButtonAgregarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelGrind, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addComponent(jPanelDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        add(jPanelVistaP, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 570, 660));
    }// </editor-fold>//GEN-END:initComponents

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed

    }//GEN-LAST:event_formMousePressed

    private void formAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_formAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_formAncestorAdded

    private void jButtonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonBuscarActionPerformed

    private void jButtonAgregarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAgregarProductoActionPerformed
        AgregarProductoJPanel jpanelAgregarProducto = new AgregarProductoJPanel();
        
        jpanelAgregarProducto.setSize(jPanelVistaP.getSize());
        jpanelAgregarProducto.setLocation(0, 0);
        jPanelVistaP.removeAll();
        jPanelVistaP.add(jpanelAgregarProducto);
       jPanelVistaP.revalidate();
        jPanelVistaP.repaint();
   
    }//GEN-LAST:event_jButtonAgregarProductoActionPerformed

   

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAgregarProducto;
    private javax.swing.JButton jButtonBuscar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JPanel jPanelDescripcion;
    private javax.swing.JPanel jPanelGrind;
    private javax.swing.JPanel jPanelVistaP;
    private javax.swing.JTextField jTextFieldBuscar;
    // End of variables declaration//GEN-END:variables
}
